services:
  db:
    image: postgres:17
    container_name: ${CONTAINER_NAME_DB}
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    expose:
      - ${DATABASE_PORT}
    networks:
      - dashboard-company-network
    volumes:
      - postgres-data:/var/lib/postgres/data

  pg-admin:
    image: dpage/pgadmin4
    container_name: ${CONTAINER_NAME_PGADMIN}
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_USER: ${PGADMIN_DEFAULT_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_DEFAULT_PORT}
    expose:
      - ${PGADMIN_PORT}
    depends_on:
      - db
    networks:
      - dashboard-company-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data

  dashboard-company:
    image: flaviojunior/dashboard-company
    container_name: ${CONTAINER_NAME_BACKEND}
    restart: always
    build: ./back-end
    working_dir: /back-end/
    environment:
      TIME_ZONE: ${TIME_ZONE}
      SECRET-KEY: ${SECRET_KEY}
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DATABASE_URL_PROD}:${DATABASE_PORT}/${DATABASE_NAME}?useTimezone=true&serverTimezone=${TIME_ZONE}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - dashboard-company-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  dashboard-company-network:
    driver: bridge