services:
  postgres-sql:
    image: postgres:17
    container_name: digital_order_postgres_17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_digital_order_test
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - digital-order-network
    volumes:
      - db-digital-order-:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    container_name: digital_order_pgadmin_4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: john.doe@example.com
      PGADMIN_DEFAULT_USER: john
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5433:80"
    expose:
      - 5433
    depends_on:
      - postgres-sql
    networks:
      - digital-order-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data

volumes:
  db-digital-order-:
  pgadmin-data:

networks:
  digital-order-network:
    driver: bridge