server:
  port : ${SERVER_PORT_PROD}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_URL_PROD}:${DATABASE_PORT_PROD}/${DATABASE_NAME_PROD}?useTimezone=true&serverTimezone=${TIME_ZONE}
    username: ${DATABASE_USERNAME_PROD}
    password: ${DATABASE_PASSWORD_PROD}
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false