server:
  port : ${SERVER_PORT_DEV}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_URL_DEV}:${DATABASE_PORT_DEV}/${DATABASE_NAME_DEV}?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: ${DATABASE_USERNAME_DEV}
    password: ${DATABASE_PASSWORD_DEV}
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true