aws:
  access_key_id: ${AWS_KEY:empty}
  secret_access_key: ${AWS_SECRET:empty}
s3:
  bucket: ${BUCKET_NAME:empty}
  region: ${BUCKET_REGION:empty}
security:
  jwt:
    token:
      secret-key: ${SECRET-KEY}
      expire-length: ${EXPIRE_TOKEN_TIME:86400000}
email:
  password-recover:
    token:
      minutes: ${PASSWORD_RECOVER_TOKEN_MINUTES:5}
spring:
  jackson:
    time-zone: ${TIME_ZONE}
  profiles:
    active: ${APP_PROFILE:prod}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:200MB}
      max-request-size: ${MAX_FILE_SIZE:200MB}
spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true