security:
  jwt:
    token:
      secret-key: ${SECRET-KEY}
      expire-length: ${EXPIRE_TOKEN_TIME:86400000}
email:
  password-recover:
    token:
      minutes: ${PASSWORD_RECOVER_TOKEN_MINUTES:5}
spring:
  jackson:
    time-zone: ${TIME_ZONE}
  profiles:
    active: ${APP_PROFILE:prod}
spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true